all:
	@cd imx662;  make || exit $$?;
	@cd imx676;  make || exit $$?;
	@cd imx678;  make || exit $$?;

clean:
	@cd imx662;   make clean;
	@cd imx676;   make clean;
	@cd imx678;   make clean;

modules_install:
	@cd imx662;   make modules_install;
	@cd imx676;   make modules_install;
	@cd imx678;   make modules_install;

